import ArrowLeftSvg from './generated/ArrowLeft';
import ArrowRightSvg from './generated/ArrowRight';
import CheckCircleSvg from './generated/CheckCircle';
import ChevronLeftSvg from './generated/ChevronLeft';
import ChevronRightSvg from './generated/ChevronRight';
import EyeSvg from './generated/Eye';
import EyeOffSvg from './generated/EyeOff';
import FileTextSvg from './generated/FileText';
import FlashlightSvg from './generated/Flashlight';
import FolderSvg from './generated/Folder';
import GearSvg from './generated/Gear';
import GiftSvg from './generated/Gift';
import ImageSvg from './generated/Image';
import InfoSvg from './generated/Info';
import KeySvg from './generated/Key';
import LockSvg from './generated/Lock';
import MailSvg from './generated/Mail';
import MonitorSvg from './generated/Monitor';
import PencilSvg from './generated/Pencil';
import PhoneSvg from './generated/Phone';
import PlusSvg from './generated/Plus';
import QrcodeSvg from './generated/Qrcode';
import ScanSvg from './generated/Scan';
import ShareSvg from './generated/Share';
import ShieldSvg from './generated/Shield';
import TabletSvg from './generated/Tablet';
import TelegramSvg from './generated/Telegram';
import TrashSvg from './generated/Trash';
import UploadSvg from './generated/Upload';
import XLogoSvg from './generated/XLogo';
import { createIcon } from './createIcon';

export { createIcon } from './createIcon';
export const ArrowLeft = createIcon(ArrowLeftSvg);
export const ArrowRight = createIcon(ArrowRightSvg);
export const CheckCircle = createIcon(CheckCircleSvg);
export const ChevronLeft = createIcon(ChevronLeftSvg);
export const ChevronRight = createIcon(ChevronRightSvg);
export const Eye = createIcon(EyeSvg);
export const EyeOff = createIcon(EyeOffSvg);
export const FileText = createIcon(FileTextSvg);
export const Flashlight = createIcon(FlashlightSvg);
export const Folder = createIcon(FolderSvg);
export const Gear = createIcon(GearSvg);
export const Gift = createIcon(GiftSvg);
export const Image = createIcon(ImageSvg);
export const Info = createIcon(InfoSvg);
export const Key = createIcon(KeySvg);
export const Lock = createIcon(LockSvg);
export const Mail = createIcon(MailSvg);
export const Monitor = createIcon(MonitorSvg);
export const Pencil = createIcon(PencilSvg);
export const Phone = createIcon(PhoneSvg);
export const Plus = createIcon(PlusSvg);
export const Qrcode = createIcon(QrcodeSvg);
export const Scan = createIcon(ScanSvg);
export const Share = createIcon(ShareSvg);
export const Shield = createIcon(ShieldSvg);
export const Tablet = createIcon(TabletSvg);
export const Telegram = createIcon(TelegramSvg);
export const Trash = createIcon(TrashSvg);
export const Upload = createIcon(UploadSvg);
export const XLogo = createIcon(XLogoSvg);
export type { IconProps } from './types';
