import ArrowLeftIcon from 'lucide-react-native/icons/arrow-left';
import ArrowRightIcon from 'lucide-react-native/icons/arrow-right';
import CheckCircleIcon from 'lucide-react-native/icons/circle-check';
import ChevronLeftIcon from 'lucide-react-native/icons/chevron-left';
import ChevronRightIcon from 'lucide-react-native/icons/chevron-right';
import EyeIcon from 'lucide-react-native/icons/eye';
import EyeOffIcon from 'lucide-react-native/icons/eye-off';
import FileTextIcon from 'lucide-react-native/icons/file-text';
import FlashlightIcon from 'lucide-react-native/icons/flashlight';
import FolderIcon from 'lucide-react-native/icons/folder';
import ImageIcon from 'lucide-react-native/icons/image';
import InfoIcon from 'lucide-react-native/icons/info';
import KeyIcon from 'lucide-react-native/icons/key-round';
import LockIcon from 'lucide-react-native/icons/lock';
import MailIcon from 'lucide-react-native/icons/mail';
import MonitorIcon from 'lucide-react-native/icons/monitor';
import PencilIcon from 'lucide-react-native/icons/pencil';
import PhoneIcon from 'lucide-react-native/icons/phone';
import PlusIcon from 'lucide-react-native/icons/plus';
import QrCodeIcon from 'lucide-react-native/icons/qr-code';
import ScanIcon from 'lucide-react-native/icons/scan';
import SendIcon from 'lucide-react-native/icons/send';
import SettingsIcon from 'lucide-react-native/icons/settings';
import ShareIcon from 'lucide-react-native/icons/share-2';
import ShieldIcon from 'lucide-react-native/icons/shield';
import TabletIcon from 'lucide-react-native/icons/tablet';
import TrashIcon from 'lucide-react-native/icons/trash';
import UploadIcon from 'lucide-react-native/icons/upload';
import XIcon from 'lucide-react-native/icons/x';
import { createIcon } from './createIcon';

export { createIcon } from './createIcon';
export const ArrowLeft = createIcon(ArrowLeftIcon);
export const ArrowRight = createIcon(ArrowRightIcon);
export const CheckCircle = createIcon(CheckCircleIcon);
export const ChevronLeft = createIcon(ChevronLeftIcon);
export const ChevronRight = createIcon(ChevronRightIcon);
export const Eye = createIcon(EyeIcon);
export const EyeOff = createIcon(EyeOffIcon);
export const FileText = createIcon(FileTextIcon);
export const Flashlight = createIcon(FlashlightIcon);
export const Folder = createIcon(FolderIcon);
export const Gear = createIcon(SettingsIcon);
export const Image = createIcon(ImageIcon);
export const Info = createIcon(InfoIcon);
export const Key = createIcon(KeyIcon);
export const Lock = createIcon(LockIcon);
export const Mail = createIcon(MailIcon);
export const Monitor = createIcon(MonitorIcon);
export const Pencil = createIcon(PencilIcon);
export const Phone = createIcon(PhoneIcon);
export const Plus = createIcon(PlusIcon);
export const Qrcode = createIcon(QrCodeIcon);
export const Scan = createIcon(ScanIcon);
export const Share = createIcon(ShareIcon);
export const Shield = createIcon(ShieldIcon);
export const Tablet = createIcon(TabletIcon);
export const Telegram = createIcon(SendIcon);
export const Trash = createIcon(TrashIcon);
export const Upload = createIcon(UploadIcon);
export const XLogo = createIcon(XIcon);
export type { IconProps } from './types';
