name: 'Check Workflow Status'
description: 'Check if a specific workflow run succeeded and get its run ID'

inputs:
  workflow-name:
    description: 'Name of the workflow to check'
    required: true
  branch:
    description: 'Branch name to check (defaults to github.head_ref)'
    required: false
    default: '${{ github.head_ref }}'

outputs:
  workflow-run-id:
    description: 'The workflow run ID if successful'
    value: ${{ steps.check-workflow.outputs.workflow-run-id }}
  conclusion:
    description: 'The workflow conclusion'
    value: ${{ steps.check-workflow.outputs.conclusion }}

runs:
  using: 'composite'
  steps:
    - name: Check Workflow Status
      id: check-workflow
      shell: bash
      run: |
        # Get the latest workflow run for this PR/branch
        WORKFLOW_RUN_ID=$(gh api repos/${{ github.repository }}/actions/runs \
          --jq '.workflow_runs[] | select(.head_branch == "${{ inputs.branch }}" and .name == "${{ inputs.workflow-name }}") | .id' \
          --paginate | head -1)
        
        if [ -z "$WORKFLOW_RUN_ID" ]; then
          echo "No ${{ inputs.workflow-name }} workflow run found for branch ${{ inputs.branch }}"
          exit 1
        fi
        
        # Check if the workflow run was successful
        CONCLUSION=$(gh api repos/${{ github.repository }}/actions/runs/$WORKFLOW_RUN_ID --jq '.conclusion')
        
        if [ "$CONCLUSION" != "success" ]; then
          echo "${{ inputs.workflow-name }} workflow failed with conclusion: $CONCLUSION"
          exit 1
        fi
        
        echo "${{ inputs.workflow-name }} workflow succeeded"
        echo "workflow-run-id=$WORKFLOW_RUN_ID" >> $GITHUB_OUTPUT
        echo "conclusion=$CONCLUSION" >> $GITHUB_OUTPUT
