name: Android E2E Tests
description: 'Disabled for now due to instability - UiAutomator2 crash'

on:
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:
    inputs:
      commit-sha:
        description: 'Commit SHA to test (leave empty to use current branch head)'
        required: false
        type: string

env:
  TERM: xterm-256color
  FORCE_COLOR: 1

jobs:
  android-e2e:
    runs-on: [self-hosted, linux]
    #runs-on: ubuntu-22.04 # [self-hosted, linux]
    concurrency:
      group: android-e2e-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      env:
        NODE_OPTIONS: "--max-old-space-size=8192"
      with:
        cache: 'yarn'
        node-version: '24.0.0'

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '20'
        distribution: 'zulu'

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Install Appium drivers
      run: yarn e2e:drivers


    - name: Wait for Android Build
      id: wait-android-build
      uses: ./.github/actions/wait-for-workflow
      with:
        workflow-name: 'Android Build'
        #commit-sha: ${{ github.event.inputs.commit-sha || github.event.pull_request.head.sha || github.sha }}
        commit-sha: ebf94f743b47a4809cf2bca1aeb30db0173107d5
        #commit-sha: f8fcc7d720f25acd8687bca5d548c400b1020ec6
        max-attempts: '360'  # 1 hour with 10s intervals

    - name: Download Android APK
      uses: dawidd6/action-download-artifact@v4
      with:
        name: android-release-apk
        path: ./artefacts
        workflow: android-build.yml
        run_id: ${{ steps.wait-android-build.outputs.workflow-run-id }}

    - name: Run E2E tests on Android emulator
      uses: reactivecircus/android-emulator-runner@v2.34.0
      env:
        ANDROID_APP: ./artefacts/app-debug.apk
        ANDROID_DEVICE_NAME: Pixel_6
      with:
        profile: pixel_6
        force-avd-creation: false
        api-level: Baklava
        avd-name: Pixel_6
        target: google_apis
        #emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none -camera-front none -logcat '*:*'
        emulator-options: -no-window -gpu swiftshader_indirect -no-snapshot -noaudio -no-boot-anim -camera-back none -camera-front none -logcat '*:*'
        arch: x86_64
        heap-size: 512M
        ndk: 27.1.12297006
        ram-size: 5048M
        cores: 1
        #emulator-build: 12325540
        #pre-emulator-launch-script: adb wait-for-device
        script: |
          adb reverse tcp:8081 tcp:8081
          npx react-native start &
          npx react-native run-android --binary-path='artefacts/app-debug.apk' --device=emulator-5554 --active-arch-only
          yarn e2e:android


    - name: Upload Video
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: android-e2e-video
        path: ./e2e/artefacts/
        retention-days: 7

    - name: Upload Logcat
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: android-e2e-logcat
        path: ./logcat.txt
        retention-days: 7

    - name: Upload Errors
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: android-e2e-errors
        path: ./errors.txt
        retention-days: 7

    - name: Upload Dmesg
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: android-e2e-dmesg
        path: ./dmesg.txt
        retention-days: 7

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: android-e2e-results
        path: |
          ./e2e/results/
        retention-days: 7
