name: Android E2E Tests

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      commit-sha:
        description: 'Commit SHA to test (leave empty to use current branch head)'
        required: false
        type: string

jobs:
  android-e2e:
    runs-on: ubuntu-latest
    concurrency:
      group: android-e2e-${{ github.head_ref }}
      cancel-in-progress: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    # - name: Set up Android SDK
    #   uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Install Appium drivers
      run: yarn e2e:drivers

    - name: Wait for Android Build
      id: wait-android-build
      uses: ./.github/actions/wait-for-workflow
      with:
        workflow-name: 'Android Build'
        commit-sha: ${{ github.event.inputs.commit-sha || github.event.pull_request.head.sha || github.sha }}
        max-attempts: '360'  # 1 hour with 10s intervals

    - name: Download Android APK
      uses: dawidd6/action-download-artifact@v4
      with:
        name: android-release-apk
        path: ./artifacts
        workflow: android-build.yml
        run_id: ${{ steps.wait-android-build.outputs.workflow-run-id }}

    - name: Run E2E tests on Android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        profile: pixel_6
        api-level: 34
        avd-name: Pixel_6_API_34
        arch: x86_64
        disable-animations: true
        emulator-build: 12325540
        script: |
          adb install ./artifacts/app-release.apk
          export ANDROID_APP=./artifacts/app-release.apk
          yarn e2e:android

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: android-e2e-results
        path: ./e2e/results/
        retention-days: 7
