name: Android E2E Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  android-e2e:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Enable KVM
      run: |
        echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
        sudo udevadm control --reload-rules
        sudo udevadm trigger --name-match=kvm
      shell: bash

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Wait for Android Build
      uses: lewagon/wait-on-check-action@v1.3.1
      with:
        ref: ${{ github.head_ref }}
        check-name: 'Android Build'
        wait-interval: 10

    - name: Check Android Build Status
      id: check-android-build
      uses: ./.github/actions/check-workflow-status
      with:
        workflow-name: 'Android Build'

    - name: Download Android APK
      uses: dawidd6/action-download-artifact@v4
      with:
        name: android-release-apk
        path: ./artifacts
        workflow: android-build.yml
        run_id: ${{ steps.check-android-build.outputs.workflow-run-id }}

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Run E2E tests on Android emulator
      uses: reactivecircus/android-emulator-runner@v2
      with:
        profile: pixel_6
        api-level: 34
        avd-name: Pixel_6_API_34
        arch: x86_64
        disable-animations: true
        emulator-build: 12325540
        script: |
          adb install ./artifacts/app-release.apk
          export ANDROID_APP=./artifacts/app-release.apk
          yarn e2e:android

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: android-e2e-results
        path: ./e2e/results/
        retention-days: 7
