name: Android Build

# on:
#   pull_request:
#     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: android-build-${{ github.head_ref }}
      cancel-in-progress: true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'yarn'

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Cache Gradle packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Generate Codegen
      run: |
        cd android
        ./gradlew generateCodegenArtifactsFromSchema

    - name: Use debug key for release build
      run: |
        cd android/app
        sed -i '/signingConfig signingConfigs.release/s/release/debug/' build.gradle

    - name: Build Android App
      run: |
        cd android
        ./gradlew assembleRelease
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 7
