name: Android Build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: clear yarn and gradle caches
      run: |
        rm -rf ~/.yarn
        rm -rf ~/.gradle

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        #cache: 'yarn'

    - name: Yarn Install
      run: yarn || yarn
      env:
        HUSKY: 0

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    # - name: Set up Android SDK
    #   uses: android-actions/setup-android@v3
      
    # - name: Install dependencies
    #   run: yarn install --frozen-lockfile
      
    # - name: Cache Gradle packages
    #   uses: actions/cache@v4
    #   with:
    #     path: |
    #       ~/.gradle/caches
    #       ~/.gradle/wrapper
    #     key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
    #     restore-keys: |
    #       ${{ runner.os }}-gradle-

    # - name: Create assets directory
    #   run: mkdir -p android/app/src/main/assets

    # - name: Bundle JavaScript
    #   run: |
    #     npx react-native bundle \
    #       --platform android \
    #       --dev false \
    #       --entry-file index.js \
    #       --bundle-output android/app/src/main/assets/index.android.bundle \
    #       --assets-dest android/app/src/main/res/

    - name: Make Gradlew Executable
      run: chmod +x android/gradlew
      
    # - name: Clean gradle cache
    #   run: |
    #     cd android
    #     ./gradlew clean

    # - name: Bundle Android App
    #   run: |
    #     npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.jsbundle --assets-dest android/app/build/intermediates/res/merged/release/

    - name: Build Android App
      run: |
        cd android
        ./gradlew app:assembleRelease || ./gradlew app:assembleRelease
      env:
        ANDROID_HOME: ${{ env.ANDROID_SDK_ROOT }}
        NEW_ARCH_ENABLED: 0
        REACT_NATIVE_ARCHITECTURE: "legacy"

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: android-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        retention-days: 7
